import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Appmigo Privacy Policy — how we collect, use, and protect your data across our games and website.',
}

const sections = [
  { id: 'introduction', title: '1. Introduction', content:
    'Welcome to the Appmigo Privacy Policy. This policy explains how Appmigo ("Appmigo", "we", "us") collects, uses, and protects information when you visit our website and/or use the games and applications offered by Appmigo, including:\n\n• Speed Memory Challenge (package: com.appmigo.speedmemorychallenge)\n• Tile Debt (package: com.appmigo.tiledebt)\n\n(collectively, the "Games" or "Services").\n\nYour privacy is important to us, and as described in this Privacy Policy, we have designed our Services to protect your information from unauthorized disclosure. This Privacy Policy explains how we collect, use and, in certain circumstances, share your information. Please read it carefully, and if you have any questions, feel free to contact us.\n\nBy downloading, accessing, or using any of our Games or Services, you agree to this Privacy Policy and consent to the collection and use of your information as described in it. This policy may be amended from time to time; if we update it, we will update the "Last updated" date on this page and post a notice on our website. We encourage you to review this page periodically.\n\nThis Privacy Policy is framed in view of the Information Technology Act, 2000 read with Regulation 4 of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and is designed to comply with applicable privacy laws including the GDPR and the CCPA where relevant.' },
  { id: 'types-of-information', title: '2. Types of Information', content:
    'Personal Information: Information that may be used to identify an individual, including, but not limited to, name, email address, phone number, or other contact information. We do not collect Personal Information unless you voluntarily provide it to us (for example, by contacting us via email or the contact form). We limit the collection of Personal Information to that which is necessary for its intended purpose.\n\nNon-Personal Information: Information that does not specifically identify an individual, such as device model, operating system version, IP address, browser type, and app usage data. The Company may gather Non-Personal Information such as how many people visit the website, the pages they visit, and the type of browser they used.\n\nUsage Information: Data and information collected automatically through the Games or through third-party analytics and advertising service providers, including system administrative data, statistical and demographic data, and operational information characterizing the use of the Games, such as game scores, progress, levels completed, and achievements.\n\nPersonal Information, Non-Personal Information, and Usage Information are hereinafter referred to as "Information".' },
  { id: 'what-we-collect', title: '3. What We Collect', content:
    'Appmigo gives you control over the information you provide. Here is what we collect:\n\nWhen You Contact Us: If you email us at support.appmigo@gmail.com, use our website contact form, or request account deletion, we collect the contact information you provide (such as your email address) solely to respond to your request. We do not sell or share this information.\n\nWhen You Play Our Games: The Games store game data (scores, progress, settings) locally on your device. We do not store this data on our servers.\n\nDevice Permissions: The Games request the following permissions:\n\n• Internet Access: Required for advertisements and game functionality\n• Vibration: For haptic feedback during gameplay\n\nWe do not collect precise location data, contacts, SMS/call data, photos, microphone, or camera data.\n\nNo Account Creation: Our Games do not require or support account creation. All game data is stored locally on your device. We do not knowingly collect Personal Information such as your name, email address, or phone number unless you voluntarily contact us.' },
  { id: 'children-under-13', title: '4. Children Under the Age of 13', content:
    'Speed Memory Challenge is designed for a general audience and may be used by children under the age of 13. We do not knowingly collect or solicit personal information from anyone under the age of 13.\n\nFor Speed Memory Challenge, we comply with the Children\'s Online Privacy Protection Act (COPPA) and Google Play\'s Families policies. We do not collect personal information from children, and we serve non-personalized advertising only to users we know or have reason to believe are under the age of 13.\n\nTile Debt is not directed at children under the age of 13 and is intended for a general audience aged 13 and above.\n\nIn the event that we learn that we have collected personal information from a child under the age of 13, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under the age of 13, please contact us at support.appmigo@gmail.com.' },
  { id: 'children-13-18', title: '5. Children Between the Ages of 13 and 18', content:
    'We recommend that minors over the age of 13 ask their parents for permission before sending any information about themselves over the Internet.' },
  { id: 'how-we-use', title: '6. How We Use Your Information', content:
    'We do not sell or rent your Personally Identifiable Information to any third party. We may use Non-Personal and Usage Information to:\n\n• Operate, manage, and maintain the Games and Services\n• Resolve any glitches or technical problems\n• Improve the Games, Services, and content\n• Create internal reports and aggregate analytics\n• Provide and improve customer support\n\nAdvertisements: Our Games use Google AdMob to display advertisements. The following ad formats are used:\n\n• Banner advertisements - Always visible during gameplay\n• Interstitial advertisements - Shown periodically between games\n• Rewarded video advertisements - User-initiated for bonuses (Continue Game, 2x Coins, Free Coins, Lucky Spin, Extra Life)\n• Rewarded interstitial advertisements - User-initiated for bonuses (Level Up Bonus, Mystery Box, Streak Reward, Power-Ups)\n• App open advertisements - Shown when launching the application\n\nAdMob may collect and use data including device identifiers (such as advertising ID), IP address, app usage data, general location data (country/region level only), and device information (model, OS version). AdMob is a certified ad SDK for Google Play.\n\nConsent: With your consent, where required, we request consent for personalized advertising using Google\'s consent management tooling (for example, the User Messaging Platform) in accordance with GDPR. Users can decline personalized advertising at any time.\n\nPush Notifications: Our Games do not send push notifications.\n\nLegal Compliance: We may access, preserve, and disclose any Information we may have about you if required to do so by law or in a good faith belief that such access, preservation, or disclosure is reasonably necessary to comply with legal process (such as a subpoena or court order), to protect our rights and property or that of our affiliates or the public, or when there is a violation of our Terms of Service.' },
  { id: 'your-choices', title: '7. Your Choices', content:
    'Opting Out of Personalized Ads: You can opt out of personalized advertising by:\n\n• Visiting Google Ads Settings: https://adssettings.google.com\n• Resetting your advertising ID in your device settings\n• Enabling "Opt out of Ads Personalization" on your Android device\n• Declining consent requests where presented\n\nUninstall: You can stop all collection of information by the Games at any time by uninstalling them. You may use the standard uninstall processes available on your mobile device or via the application marketplace.\n\nAccount Deletion: Our Games do not offer account creation, and we do not store personal data on our servers. However, if you have contacted us or provided us with personal information and wish to have it deleted, you can request complete deletion of your data at: https://appmigo.vercel.app/account-deletion or by emailing privacy@appmigo.com. We will process deletion requests within 30 days and permanently delete your data, except where we are required to retain certain data for legitimate legal, security, or regulatory reasons, in which case we will inform you of the applicable retention period. Account freezing is not used as a substitute for deletion.' },
  { id: 'data-safety', title: '8. Google Play Data Safety', content:
    'Google Play requires every app to complete and maintain an accurate Data safety section in the Play Console. The declarations in our Data safety section are consistent with the disclosures in this Privacy Policy. For each game, our Data safety section discloses the types of data collected (including device or other identifiers, app activity, and advertising data via AdMob) and how that data is used and shared. This privacy policy is available at a publicly accessible, non-geofenced URL and is not editable by users.' },
  { id: 'data-sharing', title: '9. Data Sharing', content:
    'We use third-party advertising companies (Google AdMob) to serve ads in our Games. Our Games do not provide any Personally Identifiable Information to third-party advertising companies.\n\nThe Application utilizes third-party services that have their own Privacy Policy about handling data:\n\n• Google Play Services\n• AdMob\n\nWe may disclose Information as required by law, such as to comply with a subpoena or similar legal process; when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request; or with trusted service providers who work on our behalf, do not have an independent right to use the information disclosed to them, and have agreed to adhere to the rules set forth in this privacy statement.' },
  { id: 'cookies', title: '10. Cookies', content:
    'To enhance your experience with our website, some web pages may use "cookies" and pixel tags. Cookies are text files placed in your browser to store your preferences. Cookies, by themselves, do not tell us your email address or other personally identifiable information unless you choose to provide it. We use cookies to understand site usage and improve the content and offerings of the website. Cookies may also be placed by third parties, the use of which we do not control. If your browser permits, you may decline cookies; however, some features of the website may not function properly without them.' },
  { id: 'security', title: '11. Security', content:
    'Our Games store all game data locally on your device; we do not maintain databases of personal user data. Any information transmitted to us (for example, via email or the contact form) is handled using commercially reasonable security practices, including encryption where applicable. However, no method of transmission over the Internet or wireless communication is completely secure, and we cannot guarantee the absolute security of information transmitted to us. Any information you transmit to us is done at your own risk.' },
  { id: 'data-retention', title: '12. Data Retention', content:
    'Game data (scores, progress, settings) is stored locally on your device and is retained for as long as you use the Games. You can delete this data at any time by uninstalling the Games or clearing app data from your device settings.\n\nInformation you provide to us directly (such as support inquiries) is retained only as long as necessary to fulfill the purpose for which it was provided, after which it is deleted. If we need to retain certain data for legitimate reasons such as security, fraud prevention, or regulatory compliance, we will clearly inform you of the applicable retention period. Data deletion requests are processed within 30 days.' },
  { id: 'your-rights', title: '13. Your Data Rights (GDPR/CCPA)', content:
    'Depending on your jurisdiction, you may have certain rights regarding your personal data:\n\n• Right to Access: You can request information about what data we hold about you\n• Right to Rectification: You can request correction of inaccurate or incomplete data\n• Right to Erasure: You can request deletion of your personal data\n• Right to Restrict Processing: You can request limitation of how we use your data\n• Right to Data Portability: You can request transfer of your data to another service\n• Right to Object: You can object to certain types of data processing\n\nCalifornia Residents (CCPA): Under the California Consumer Privacy Act, you have the right to know, delete, and opt-out of the sale of personal information. We do not sell personal information.\n\nTo exercise any of these rights, please contact us at support.appmigo@gmail.com or submit a deletion request at https://appmigo.vercel.app/account-deletion. We will respond to your request within 30 days.' },
  { id: 'contact', title: '14. Contacting Us', content:
    'If you have any questions regarding privacy while using our Games, or have questions about our practices, please contact us:\n\n• Email: support.appmigo@gmail.com\n• Privacy: privacy@appmigo.com\n• Contact Form: https://appmigo.vercel.app/contact\n• Account Deletion: https://appmigo.vercel.app/account-deletion\n\nAll correspondence received by us from you is classified as restricted-access information and may not be disclosed without your written consent, except as expressly provided by law.' },
]

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16 sm:py-20">
      <h1 className="font-heading text-4xl sm:text-5xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-3 text-sm text-muted-foreground">Last updated: August 10, 2026</p>

      <nav className="mt-10 mb-14 p-5 rounded-xl border bg-card">
        <h2 className="font-heading font-semibold text-sm mb-3">Contents</h2>
        <ul className="space-y-1">
          {sections.map(s => (
            <li key={s.id}>
              <a href={`#${s.id}`} className="text-sm text-primary hover:underline">{s.title}</a>
            </li>
          ))}
        </ul>
      </nav>

      <div className="space-y-12">
        {sections.map(s => (
          <section key={s.id} id={s.id}>
            <h2 className="font-heading text-xl font-semibold mb-4">{s.title}</h2>
            <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{s.content}</div>
          </section>
        ))}
      </div>
    </div>
  )
}
